### ISSUE TITLE
[BUG] high-entropy strings are ignored under certain circumstances

### ISSUE THREAD

**Issue by 0xDokki** [IBM/detect-secrets#87]
## Describe the bug

High entropy strings that are part of a yaml structure (e.g. secret definitions pulled from openshift) will be detected by `detect-secrets` ***if and only if*** the file has a `.yaml` extension.

This was first encountered on version  `0.13.1+ibm.47.dss`, but also verified on the latest,  `0.13.1+ibm.48.dss`.

**Note:** This issue is mostly for record-keeping and gathering feedback, we're internally planning for a member of our team to pick this up and raise a PR to fix the bug.

## To Reproduce

> **Keep calm**: the value below is derived from an actual secret insofar that it retains the internal structure and approximate entropy  both encoded and decoded, **however** the secret values have been replaced by dummy strings in the form of `abcd1234`. In the tests described further below, these dummy values result in an entropy approximately 0.1 higher than the original values.
> 
> In addition to the (fake) actual secret, I also added a line that will trigger keyword based detection.

```yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJ1cy5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgInVrLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiZGUuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJhdS5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgImpwLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAicHJpdmF0ZS5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgInByaXZhdGUudXMuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLnVrLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAicHJpdmF0ZS5kZS5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgInByaXZhdGUuYXUuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmpwLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiYnIuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmJyLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiY2EuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmNhLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiZnIyLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAicHJpdmF0ZS5mcjIuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJqcDIuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmpwMi5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifX19
kind: Secret
metadata:
  name: my-downloaded-secret
  namespace: my-namespace
  apiKey: <test for keyword-based detection>
type: kubernetes.io/dockerconfigjson
```

1. Save the above example yaml in a file `test.yaml`
2. Run `git add test.yaml`
3. Run `detect-secrets scan --update .secrets.baseline`
4. The `.secrets.baseline` file now shows both a high entropy string, as well as a keyword detection
5. Rename `test.yaml` to `test.txt`
6. Run `git add test.yaml test.txt`
7. Run `detect-secrets scan --update .secrets.baseline`
8. In `.secrets.baseline`, the high entropy detection is now gone, only the keyword detection remains

## Expected behavior

Detection of high-entropy strings should not depend on file extension. The example above should either trigger both keyword *and* entropy based detection or neither, but never just one of the two.

## Actual Behaviour

The keyword based detection for the `apiKey` line always triggers, pretty much regardless of what file extension is given to the file, and even when there's no extension at all. The only exception here seems to be when the file has an extension that explicitly identifies it as a binary file, e.g. `.png`.

On the other hand the high-entropy-string detection *in this case* only triggers when the file has a `.yaml` extension.

## Impact

From my testing (more on that in the next section) this only affects files in yaml structure, which limits the impact.

On the other hand, false negatives seem like a rather high impact bug in the context of secret detection.

## Additional context:

The realization that this somehow must be related to the yaml structure occurred when I did the following test.
I took the entropy function from the detect-secrets codebase, and ran it on the secret on it's own (like it would be if it had been parsed as a yaml value), as well as the entire line including the yaml prefix.

```py
def calculate_shannon_entropy(data):
    # entropy function taken from detect-secrets codebase
    # https://github.com/IBM/detect-secrets/blob/master/detect_secrets/plugins/high_entropy_strings.py#L73
    # ...
    return entropy

value = "eyJhdXRocyI6IHsiaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJ1cy5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgInVrLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiZGUuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJhdS5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgImpwLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAicHJpdmF0ZS5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgInByaXZhdGUudXMuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLnVrLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAicHJpdmF0ZS5kZS5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifSwgInByaXZhdGUuYXUuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmpwLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiYnIuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmJyLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiY2EuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmNhLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAiZnIyLmljci5pbyI6IHsiYXV0aCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0NTY3ODkiLCAidXNlcm5hbWUiOiAiaWFtYXBpa2V5IiwgImVtYWlsIjogImlhbWFwaWtleSIsICJwYXNzd29yZCI6ICJhYmNkZWZnaGlqa2xtbm9wcHFyc3R1dnd4eXoxMjM0NTY3ODkwQUJDREVGRyJ9LCAicHJpdmF0ZS5mcjIuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJqcDIuaWNyLmlvIjogeyJhdXRoIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OSIsICJ1c2VybmFtZSI6ICJpYW1hcGlrZXkiLCAiZW1haWwiOiAiaWFtYXBpa2V5IiwgInBhc3N3b3JkIjogImFiY2RlZmdoaWprbG1ub3BwcXJzdHV2d3h5ejEyMzQ1Njc4OTBBQkNERUZHIn0sICJwcml2YXRlLmpwMi5pY3IuaW8iOiB7ImF1dGgiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiYWJjZGVmZ2hpamtsbW5vcHBxcnN0dXZ3eHl6MTIzNDU2Nzg5MEFCQ0RFRkcifX19"

print(f"value on its own: {calculate_shannon_entropy(value)}")
print(f"full line: {calculate_shannon_entropy('  .dockerconfigjson: ' + value)}")
```

Producing the following result:

```
value on its own: 5.702578292302313
full line: 5.7002888259722795
```

Not only is there hardly any difference, but both are well above the threshold of 4.5.

The thing that actually lead to the aforementioned realization however was that *the same secret value*, just in a python script with less prefix, was now being picked up reliably by detect-secrets, the same way that the keyword based one was previously (i.e. in all cases except when the extension identified the file as binary).

---

Addendum: I eventually realized that the 'encoded secret' is in fact simply a base64-encoded json structure, that in addition to the secrets themselves also contains a bunch of meta information like endpoints etc. As a result, decoding it may lower the entropy significantly.

I have thus ammended my python test as follows:

```py
print(f"decoded value: {calculate_shannon_entropy(str(base64.b64decode(value)))}")
print(f"(decoded value) + prefix: {calculate_shannon_entropy('  .dockerconfigjson: ' + str(base64.b64decode(value)))}")
print(f"decoded (value + prefix): {calculate_shannon_entropy(str(base64.b64decode('  .dockerconfigjson: ' + value)))}")
```

With the following results:

```
decoded value: 4.7900574992342255
(decoded value) + prefix: 4.788563031090121
decoded (value + prefix): 4.803569874982614
```

Those entropies *are* significantly lower, however all of them are still above the threshold of 4.5, so to my understanding should all still trigger the detection, so there must be another puzzle piece I'm missing here.
